sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t legendlight/react-project/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true legendlight/react-project/react-test npm test

after_success:
  - docker build -t legendlight/react-project/multi-client ./client
  - docker build -t legendlight/react-project/multi-nginx ./nginx
  - docker build -t legendlight/react-project/multi-server ./server
  - docker build -t legendlight/react-project/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push legendlight/react-project/multi-client
  - docker push legendlight/react-project/multi-nginx
  - docker push legendlight/react-project/multi-server
  - docker push legendlight/react-project/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-southeast-2'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#   bucket_path: 'docker-multi'
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
